// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppDateTime: typeof import('./src/components/AppDateTime.vue')['default']
    AppFolder: typeof import('./src/components/apps/AppFolder.vue')['default']
    AppItemIcon: typeof import('./src/components/apps/AppItemIcon.vue')['default']
    AppPagination: typeof import('./src/components/AppPagination.vue')['default']
    Apps: typeof import('./src/components/Apps.vue')['default']
    AppSearch: typeof import('./src/components/AppSearch.vue')['default']
    AppSentences: typeof import('./src/components/AppSentences.vue')['default']
    AppTab: typeof import('./src/components/AppTab.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    Calendar: typeof import('./src/components/apps/Calendar.vue')['default']
    CreateApp: typeof import('./src/components/CreateApp.vue')['default']
    CreateNewApp: typeof import('./src/components/CreateNewApp.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    EditApp: typeof import('./src/components/EditApp.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HistoryToday: typeof import('./src/components/apps/HistoryToday.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    SettingMenu: typeof import('./src/components/SettingMenu.vue')['default']
    ShyCheckbox: typeof import('./src/components/ShyCheckbox.vue')['default']
    ShyDialog: typeof import('./src/components/ShyDialog.vue')['default']
    TodoList: typeof import('./src/components/apps/TodoList.vue')['default']
  }
}

export { }
