// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppItemIcon: typeof import('./src/components/apps/AppItemIcon.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
  }
}

export { }
