// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppDateTime: typeof import('./src/components/AppDateTime.vue')['default']
    AppItemIcon: typeof import('./src/components/apps/AppItemIcon.vue')['default']
    Apps: typeof import('./src/components/Apps.vue')['default']
    AppSearch: typeof import('./src/components/AppSearch.vue')['default']
    AppTab: typeof import('./src/components/AppTab.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
  }
}

export { }
